# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: beNice17 theme
email: beNice17@vietanhdev.com
author: Viet Anh Nguyen
description: > # this means to ignore newlines until "baseurl:"
  A minimal theme for personal website
url: "http://vietanhdev.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/beNice17" # the subpath of your site, e.g. /blog


menu:
  Home:
    link: /
    icon: "fa-home"
  My Blog:
    link: blog/
    icon: "fa-wordpress"
  My Projects:
    link: projects/
    icon: "fa-briefcase"
  Contact:
    link: contact/
    icon: "fa-info-circle"


# Sharing settings
shareimg: https://vietanhdev.com/beNice17/assets/images/sharing-imgs/beNice17.jpg # default sharing img
bigimg: images/patterns/triangular.png # default big img (header image(s))
fb_app_id: 12345 # Facebook app id

timezone: "+0700"
permalink: /posts/:title.html

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
